### PR TITLE
Updates to documentation

### PR DESCRIPTION
**Pull request by liambuchanan**

### CODE REVIEW

**Comment by imsky** [comment]
the only slight tweak i'd make to this is to outline all of the custom kronjob properties in one section, and then show them being used in different sections.

**Comment by imsky** [comment]
👍

**Comment by liambuchanan** [comment]
thanks @imsky I intend to iterate on this a bit for clarity's sake.
That's kind of what I was trying to do with features/examples. Do you think I should go for parity between features and examples to make jumping between the two easier?

**Comment by imsky** [comment]
yeah i think features needs to be much more fleshed out, i.e. "this spec field corresponds to this feature" etc.

**Pull request merged**
